name: Build & Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build with ncc
      run: |
        npm install
        npm run build

    - name: Invoke echo 1 workflow using this action
      uses: ./
      with:
        workflow: Message Echo 1
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{"commitId": "1234567"}'

    - name: Invoke echo 2 workflow using this action
      uses: ./
      with:
        workflow: echo-2.yaml
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Invoke echo 1 workflow by id
      uses: ./
      with:
        workflow: '1854247'
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{"commitId": "1234567"}'

    - name: Update repo with build
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
