name: Message Echo 2

on:
  workflow_dispatch:
    inputs:
      commitId:
        description: "Message to echo"
        required: false
        default: "this is echo 2"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo '${{ inputs.commitId }}'
