name: Message Echo 1

on:
  workflow_dispatch:
    inputs:
      commitId:
        description: "Message to echo"
        required: true
        # No default

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo '${{ inputs.commitId }}'
